# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "capstone2llvmir-X86"

[find-package.LLVM]
required = true
config = true
[find-package.Clang]
required = true
config = true

[subdir.utils]

[target.capstone2llvmir-X86]
type = "static"
sources = [
    "capstone2llvmir/**.cpp", 
    "capstone2llvmir/**.h", 
    "capstone2llvmir/x86/**.cpp",
    "capstone2llvmir/x86/**.h"
    ]
include-directories = ["${LLVM_INCLUDE_DIRS}", "${CLANG_INCLUDE_DIRS}"]
link-directories = ["${LLVM_LIBRARY_DIRS}", "${CLANG_LIBRARY_DIRS}"]
add-definitions = ["${LLVM_DEFINITIONS}", "${CLANG_DEFINITIONS}"]
link-libraries = [
"LLVMSupport", 
"LLVMAnalysis",
"LLVMCore",
"LLVMCodeGen"
]


